version: '3.4'

services:
    web:
        container_name: web
        build:
            context: .
        ports:
            - "8080:8080"
        volumes:
            - ./public:/code/public
            - ./src:/code/src
        environment:
            - NODE_ENV=development
        command: [ "yarn", "start:local" ]
